name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    uses: trancecode/github-workflows/.github/workflows/pages-deploy.yml@main
    with:
      generator: pkgsite
      package: github.com/trancecode/ecs/ecs
      go-version-file: go.mod
